:toc: left

== AsciiDoc

=== Introductie
Iedereen (van onze groep) kent Markdown. Maar er bestaan ook alternatieven om documentatie te schrijven op github. Een van deze alternatieven is Asciidoctor. In de basis werken de technieken op de zelfde manier. Toch is asciidoc beter. Het probleem van markdown dat AsciiDoc oplost is het gebrek aan features van markdown. Markdown mist allerlei functionaliteiten die je nodig hebt om echte verslagen te maken. 

=== Voordelen
AsciiDoc kan voor ons nuttig zijn omdat:

==== http://asciidoctor.org/docs/user-manual/#numbering[Automatische hoofdstuknummers]

==== http://asciidoctor.org/docs/user-manual/#table-of-contents-summary[Automatische inhoudsopgave] 


==== http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#bibliography[Bibliografie referenties ondersteunt]
Dit is een stukje tekst met een bron <<br>> naar een bepaalde plek.

==== http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#source-code[Code blokken referentie-uitleggen]
----
void test() {
  System.out.println("Hello World!"); // <1>
}
----
<1> Hier wordt hallo gezegd tegen de wereld

=== Nadelen
Nadeel is dat asciidoc net wat andere syntax heeft, dus het gebruiken van asciidoc zou een kleine leercurve met zich meebrengen.

[bibliography]
== References

- [[[br]]] Andy Hunt & Dave Thomas. The Pragmatic Programmer:
  From Journeyman to Master. Addison-Wesley. 1999.
