export const LOGIN_ACTIONS = {
  SET_LOGIN_FLAG: 'SET_LOGIN_FLAG',
  SET_LOGGED_IN_USER: 'SET_LOGGED_IN_USER',
  FETCH_USERS: 'FETCH_USERS'
};

export const VISIT_HISTORY_ACTIONS = {
  FETCH_VISIT_HISTORY: 'FETCH_VISIT_HISTORY'
};