export const SPEURPUNT_ACTION_TYPES = {
  FETCH_SPEURPUNTEN: 'FETCH_SPEURPUNTEN',
  ADD_SPEURPUNT: 'ADD_SPEURPUNT',
  UPDATE_SPEURPUNT: 'UPDATE_SPEURPUNT'
};

export const DIERENGELUIDEN_ACTION_TYPES = {
  FETCH_DIERENGELUIDEN: 'FETCH_DIERENGELUIDEN'
};

export const WEETJES_ACTION_TYPES = {
  FETCH_WEETJES: 'FETCH_WEETJES'
};

export const POTEN_ACTION_TYPES = {
  FETCH_POTEN: 'FETCH_POTEN'
};

export const VERBLIJVEN_ACTION_TYPES = {
  FETCH_VERBLIJVEN: 'FETCH_VERBLIJVEN'
};
