export const SPEURPUNT_ACTION_TYPES = {
  FETCH_SPEURPUNTEN: 'FETCH_SPEURPUNTEN'
};

export const DIERENGELUIDEN_ACTION_TYPES = {
  FETCH_DIERENGELUIDEN: 'FETCH_DIERENGELUIDEN'
};

export const WEETJES_ACTION_TYPES = {
  FETCH_WEETJES: 'FETCH_WEETJES'
};
