export const SPEURPUNT_ACTION_TYPES = {
  FETCH_SPEURPUNTEN: 'FETCH_SPEURPUNTEN',
  ADD_SPEURPUNT: 'ADD_SPEURPUNT',
  UPDATE_SPEURPUNT: 'UPDATE_SPEURPUNT'
};

export const DIERENGELUIDEN_ACTION_TYPES = {
  FETCH_DIERENGELUIDEN: 'FETCH_DIERENGELUIDEN',
  ADD_DIERENGELUID: 'ADD_DIERENGELUID'
};

export const WEETJES_ACTION_TYPES = {
  FETCH_WEETJES: 'FETCH_WEETJES',
  ADD_WEETJE: 'ADD_WEETJE'
};

export const POTEN_ACTION_TYPES = {
  FETCH_POTEN: 'FETCH_POTEN'
};

export const VERBLIJVEN_ACTION_TYPES = {
  FETCH_VERBLIJVEN: 'FETCH_VERBLIJVEN'
};

export const FILEUPLOAD_ACTION_TYPES = {
  ADD_FILE: 'ADD_FILE',
  UPLOAD_STATUS_PENDING: 'UPLOAD_STATUS_PENDING',
  UPLOAD_STATUS_SUCCESS: 'UPLOAD_STATUS_SUCCESS',
  UPLOAD_STATUS_ERROR: 'UPLOAD_STATUS_ERROR',
  SET_UPLOAD_STATUS: 'SET_UPLOAD_STATUS',
  UPLOAD_STATUS_IDLE: 'UPLOAD_STATUS_IDLE',
  SET_EMPTY_STATE: 'SET_EMPTY_STATE'
};
